// <auto-generated />
namespace ASPNETMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contexto1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contexto1));
        
        string IMigrationMetadata.Id
        {
            get { return "202211192200116_contexto1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
